### ISSUE TITLE
Hot reload doesn't work with figwheel 0.5.9

### ISSUE THREAD

**Issue by GlebkaF** [drapanjanas/re-natal#99]
Hello there! I'm faced with this issue.

Steps to reproduce:
1. `re-natal init FutureApp -i reagent6 && cd future-app`
2. Bump lein-figwheel to 0.5.9 in project.clj
3. Run the following commands:
```
re-natal use figwheel
lein figwheel ios
npm start
react-native run-ios
```

With "Debug JS remotely" enabled I get following errors in the Chrome console when I'm trying to change some code:
```
GET http://localhost:8081/future_app/ios/core.js?zx=90r15q5uqeco 404 (Not Found)
figwheel-bridge.js:172 Figwheel: Error loading file goog/../future_app/ios/core.js
figwheel-bridge.js:172 Error: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/future_app/ios/core.js?zx=90r15q5uqeco' failed to load.
    at file_reloading.js:650
    at file_reloading.js:664
    at figwheel$client$file_reloading$reload_file (file_reloading.js:685)
    at figwheel$client$file_reloading$blocking_load (file_reloading.js:713)
    at file_reloading.js:821
    at file_reloading.js:890
    at figwheel$client$file_reloading$state_machine__29937__auto____1 (file_reloading.js:911)
    at figwheel$client$file_reloading$state_machine__29937__auto__ (file_reloading.js:927)
    at cljs$core$async$impl$ioc_helpers$run_state_machine (ioc_helpers.js:94)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (ioc_helpers.js:97)
```

When remote debugging turned off app just crashes with "Reload not defined for this platform" error:

![image](https://cloud.githubusercontent.com/assets/8992139/23446981/37782056-fe7a-11e6-8a67-ab9c6b7a1bfc.png)

**Comment by tiensonqin** [comment]
It's actually a problem of figwheel.
https://github.com/bhauman/lein-figwheel/pull/524

**Comment by drapanjanas** [comment]
This is fixed in figwheel 0.5.10 and re-natal 0.4.0
